.\" cb_share_config man page. 
.\" Contact admin@codeblocks.org to correct errors or omissions. 
.TH man 1 "16 July 2007" "1.0" "cb_share_config man page"
.SH NAME
cb_share_config \- Import/export parts of Code::Blocks configuration
.SH SYNOPSIS
.\" Syntax goes here. 
.B cb_share_config
.SH DESCRIPTION
.B cb_share_config
allows you to share (import/export) parts of Code::Blocks configuration. It is
useful, for example, when you want to partially transfer settings between computers
or even between different configurations.
.SH AUTHOR
.nf
Martin Halle
.fi
.SH HISTORY
2007 \- Initial version
