.\" Code::Blocks IDE cb_console_runner man page. 
.\" Contact admin@codeblocks.org to correct errors or omissions. 
.TH man 1 "10 July 2006" "1.0" "cb_console_runner man page"
.SH NAME
cb_console_runner \- The Code::Blocks IDE console programs launcher
.SH SYNOPSIS
.\" Syntax goes here. 
.B cb_console_runner
.I args
.SH DESCRIPTION
.B cb_console_runner
is part of the Code::Blocks IDE. It is used to launch console programs
and wait for them to finish.
When the console program is finished, cb_console_runner displays 
"Press ENTER to continue".

That's its sole job.
.SH OPTIONS
No options.
.SH EXAMPLES
.nf
cb_console_runner /home/user/test_program --prog_arg1
.SH AUTHOR
.nf
Yiannis "mandrav" Mandravellos (mandrav@codeblocks.org)
.fi
.SH HISTORY
2006 \- Initial version
