#! /bin/sh
#
# This file is part of the Code::Blocks IDE and licensed under the GNU General Public License, version 3
# http://www.gnu.org/licenses/gpl-3.0.html
#
# Copyright: 2008 Jens Lody
#
# $Revision$
# $Id$
# $HeadURL$
#

mkdir -p ../../../devel/share/codeblocks/images/settings > /dev/null 2> /dev/null
mkdir -p ../../../output/share/codeblocks/images/settings > /dev/null 2> /dev/null
cp ./*.png ../../../devel/share/codeblocks/images/settings/ > /dev/null 2> /dev/null
cp ./*.png ../../../output/share/codeblocks/images/settings/ > /dev/null 2> /dev/null
exit 0

