#! /bin/sh
mkdir -p ../../../devel/share/codeblocks/images/settings > /dev/null 2> /dev/null
mkdir -p ../../../output/share/codeblocks/images/settings > /dev/null 2> /dev/null
cp ./*.png ../../../devel/share/codeblocks/images/settings/ > /dev/null 2> /dev/null
cp ./*.png ../../../output/share/codeblocks/images/settings/ > /dev/null 2> /dev/null
exit 0

