#!/bin/sh
mkdir -p ../../../devel30/share/codeblocks/images/wxsmith > /dev/null 2> /dev/null
mkdir -p ../../../output30/share/codeblocks/images/wxsmith > /dev/null 2> /dev/null
zip ../../../devel30/share/codeblocks/wxsmith.zip manifest.xml
zip ../../../output30/share/codeblocks/wxsmith.zip manifest.xml
cp ./wxwidgets/icons/*.png ../../../devel30/share/codeblocks/images/wxsmith/ > /dev/null 2> /dev/null
cp ./wxwidgets/icons/*.png ../../../output30/share/codeblocks/images/wxsmith/ > /dev/null 2> /dev/null
exit 0
