// generated by Fast Light User Interface Designer (fluid) version 1.0106

#ifndef main_ui_h
#define main_ui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
Fl_Double_Window* make_window();
#endif
