// generated by Fast Light User Interface Designer (fluid) version 1.0106

#include "main_ui.h"

Fl_Double_Window* make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(293, 216);
    w = o;
    o->end();
  }
  return w;
}
