#!/bin/bash
mkdir -p ../../../devel30/share/codeblocks/lib_finder > /dev/null 2> /dev/null
mkdir -p ../../../output30/share/codeblocks/lib_finder > /dev/null 2> /dev/null
cp ./lib_finder/*.xml ../../../devel30/share/codeblocks/lib_finder > /dev/null 2> /dev/null
cp ./lib_finder/*.xml ../../../output30/share/codeblocks/lib_finder > /dev/null 2> /dev/null
zip -j9 ../../../devel30/share/codeblocks/lib_finder.zip manifest.xml
exit 0
