#! /bin/sh
mkdir -p ../../../devel30/share/codeblocks/images/settings > /dev/null 2> /dev/null
mkdir -p ../../../output30/share/codeblocks/images/settings > /dev/null 2> /dev/null
cp ./Resources/*.png ../../../devel30/share/codeblocks/images/settings/ > /dev/null 2> /dev/null
cp ./Resources/*.png ../../../output30/share/codeblocks/images/settings/ > /dev/null 2> /dev/null
exit 0

