#! /bin/sh
mkdir -p ../../../devel29/share/codeblocks/images/settings > /dev/null 2> /dev/null
mkdir -p ../../../output29/share/codeblocks/images/settings > /dev/null 2> /dev/null
cp ./Resources/*.png ../../../devel29/share/codeblocks/images/settings/ > /dev/null 2> /dev/null
cp ./Resources/*.png ../../../output29/share/codeblocks/images/settings/ > /dev/null 2> /dev/null
exit 0

