usr/share/icons
usr/share/pixmaps
usr/share/mime
usr/share/applications

usr/share/man/man1/codeblocks.1
usr/share/man/man1/cb_console_runner.1
usr/share/man/man1/cb_share_config.1

usr/share/codeblocks/icons/
usr/share/codeblocks/images/*.png
usr/share/codeblocks/images/16x16
usr/share/codeblocks/images/codecompletion
usr/share/codeblocks/images/settings
usr/share/codeblocks/lexers
usr/share/codeblocks/scripts
usr/share/codeblocks/templates

usr/share/codeblocks/abbreviations.zip
usr/share/codeblocks/astyle.zip
usr/share/codeblocks/autosave.zip
usr/share/codeblocks/classwizard.zip
usr/share/codeblocks/codecompletion.zip
usr/share/codeblocks/compiler.zip
usr/share/codeblocks/debugger.zip
usr/share/codeblocks/defaultmimehandler.zip
usr/share/codeblocks/manager_resources.zip
usr/share/codeblocks/openfileslist.zip
usr/share/codeblocks/projectsimporter.zip
usr/share/codeblocks/resources.zip
usr/share/codeblocks/scriptedwizard.zip
usr/share/codeblocks/start_here.zip
usr/share/codeblocks/todo.zip

usr/share/codeblocks/tips.txt

../lintian/codeblocks-common  usr/share/lintian/overrides/
