usr/lib/codeblocks/wxContribItems/libwxchartctrl.so.*
usr/lib/codeblocks/wxContribItems/libwxcustombutton.so.*
usr/lib/codeblocks/wxContribItems/libwxflatnotebook.so.*
usr/lib/codeblocks/wxContribItems/libwximagepanel.so.*
usr/lib/codeblocks/wxContribItems/libwxkwic.so.*
usr/lib/codeblocks/wxContribItems/libwxled.so.*
usr/lib/codeblocks/wxContribItems/libwxspeedbutton.so.*
usr/lib/codeblocks/wxContribItems/libwxtreelist.so.*

