usr/bin/codesnippets

usr/lib/codeblocks/plugins/libAutoVersioning.so
usr/lib/codeblocks/plugins/libBrowseTracker.so
usr/lib/codeblocks/plugins/libbyogames.so
usr/lib/codeblocks/plugins/libCccc.so
usr/lib/codeblocks/plugins/libCppCheck.so
usr/lib/codeblocks/plugins/libcb_koders.so
usr/lib/codeblocks/plugins/libcodesnippets.so
usr/lib/codeblocks/plugins/libcodestat.so
usr/lib/codeblocks/plugins/libcopystrings.so
usr/lib/codeblocks/plugins/libCscope.so
usr/lib/codeblocks/plugins/libDoxyBlocks.so
usr/lib/codeblocks/plugins/libdragscroll.so
usr/lib/codeblocks/plugins/libEditorConfig.so
usr/lib/codeblocks/plugins/libEditorTweaks.so
usr/lib/codeblocks/plugins/libenvvars.so
usr/lib/codeblocks/plugins/libexporter.so
usr/lib/codeblocks/plugins/libFileManager.so
usr/lib/codeblocks/plugins/libheaderfixup.so
usr/lib/codeblocks/plugins/libhelp_plugin.so
usr/lib/codeblocks/plugins/libHexEditor.so
usr/lib/codeblocks/plugins/libIncrementalSearch.so
usr/lib/codeblocks/plugins/libkeybinder.so
usr/lib/codeblocks/plugins/liblib_finder.so
usr/lib/codeblocks/plugins/libNassiShneiderman.so
usr/lib/codeblocks/plugins/libProfiler.so
usr/lib/codeblocks/plugins/libRegExTestbed.so
usr/lib/codeblocks/plugins/libSpellChecker.so
usr/lib/codeblocks/plugins/libSymTab.so
usr/lib/codeblocks/plugins/libThreadSearch.so
usr/lib/codeblocks/plugins/libToolsPlus.so
usr/lib/codeblocks/plugins/libValgrind.so
usr/lib/codeblocks/plugins/libMouseSap.so
usr/lib/codeblocks/plugins/libReopenEditor.so
usr/lib/codeblocks/plugins/libwxsmith.so
usr/lib/codeblocks/plugins/libwxsmithcontribitems.so
usr/lib/codeblocks/plugins/libwxSmithAui.so

../lintian/codeblocks-contrib  usr/share/lintian/overrides/
usr/lib/pkgconfig/wxsmithaui.pc usr/lib/pkgconfig/
