#! /bin/sh
#

mkdir -p ../../../devel29/share/codeblocks/images/DoxyBlocks > /dev/null 2> /dev/null
mkdir -p ../../../devel29/share/codeblocks/images/DoxyBlocks/16x16 > /dev/null 2> /dev/null
mkdir -p ../../../output29/share/codeblocks/images/DoxyBlocks > /dev/null 2> /dev/null
mkdir -p ../../../output29/share/codeblocks/images/DoxyBlocks/16x16 > /dev/null 2> /dev/null
mkdir -p ../../../devel29/share/codeblocks/images/settings > /dev/null 2> /dev/null
mkdir -p ../../../output29/share/codeblocks/images/settings > /dev/null 2> /dev/null
cp ./images/*.png ../../../devel29/share/codeblocks/images/DoxyBlocks/ > /dev/null 2> /dev/null
cp ./images/16x16/*.png ../../../devel29/share/codeblocks/images/DoxyBlocks/16x16/ > /dev/null 2> /dev/null
cp ./images/*.png ../../../output29/share/codeblocks/images/DoxyBlocks/ > /dev/null 2> /dev/null
cp ./images/16x16/*.png ../../../output29/share/codeblocks/images/DoxyBlocks/16x16/ > /dev/null 2> /dev/null
cp ./*.png ../../../devel29/share/codeblocks/images/settings/ > /dev/null 2> /dev/null
cp ./*.png ../../../output29/share/codeblocks/images/settings/ > /dev/null 2> /dev/null
exit 0


