#! /bin/sh

CB_DEVEL=devel$1
CB_OUTPUT=output$1
CB_DEVEL_RESDIR=../../../$CB_DEVEL/share/codeblocks/images
CB_OUTPUT_RESDIR=../../../$CB_OUTPUT/share/codeblocks/images

# This is done this stupid/convoluted way, because dash/posix doesn't have arrays!
dirs="16x16 20x20 24x24 28x28 32x32 40x40 48x48 56x56 64x64"
echo "$dirs" | tr ' ' '\n' | while read dir; do
    mkdir -p ${CB_DEVEL_RESDIR}/DoxyBlocks/${dir}
    mkdir -p ${CB_OUTPUT_RESDIR}/DoxyBlocks/${dir}

    cp ./images/${dir}/*.png ${CB_DEVEL_RESDIR}/DoxyBlocks/${dir}/ #> /dev/null 2> /dev/null
    cp ./images/${dir}/*.png ${CB_OUTPUT_RESDIR}/DoxyBlocks/${dir}/ #> /dev/null 2> /dev/null
done

mkdir -p ${CB_DEVEL_RESDIR}/settings > /dev/null 2> /dev/null
mkdir -p ${CB_OUTPUT_RESDIR}/settings > /dev/null 2> /dev/null
cp *.png ${CB_DEVEL_RESDIR}/settings/ > /dev/null 2> /dev/null
cp *.png ${CB_OUTPUT_RESDIR}/settings/ > /dev/null 2> /dev/null

exit 0


