#! /bin/sh
#

CB_DIR="../../../devel30/share/codeblocks/"

mkdir -p ${CB_DIR}/images/DoxyBlocks/22x22 > /dev/null 2> /dev/null
mkdir -p ${CB_DIR}/images/DoxyBlocks/16x16 > /dev/null 2> /dev/null
mkdir -p ${CB_DIR}/images/settings > /dev/null 2> /dev/null
cp ./images/22x22/*.png ${CB_DIR}/images/DoxyBlocks/22x22 > /dev/null 2> /dev/null
cp ./images/16x16/*.png ${CB_DIR}/images/DoxyBlocks/16x16/ > /dev/null 2> /dev/null
cp ./*.png ${CB_DIR}/images/settings/ > /dev/null 2> /dev/null

CB_DIR="../../../output30/share/codeblocks/"

mkdir -p ${CB_DIR}/images/DoxyBlocks/22x22 > /dev/null 2> /dev/null
mkdir -p ${CB_DIR}/images/DoxyBlocks/16x16 > /dev/null 2> /dev/null
mkdir -p ${CB_DIR}/images/settings > /dev/null 2> /dev/null
cp ./images/22x22/*.png ${CB_DIR}/images/DoxyBlocks/22x22 > /dev/null 2> /dev/null
cp ./images/16x16/*.png ${CB_DIR}/images/DoxyBlocks/16x16/ > /dev/null 2> /dev/null
cp ./*.png ${CB_DIR}/images/settings/ > /dev/null 2> /dev/null

exit 0


