#! /bin/sh

CB_DEVEL=devel$1
CB_OUTPUT=output$1
CB_DEVEL_RESDIR=../../../$CB_DEVEL/share/codeblocks/images
CB_OUTPUT_RESDIR=../../../$CB_OUTPUT/share/codeblocks/images

mkdir -p ${CB_DEVEL_RESDIR}/settings > /dev/null 2> /dev/null
mkdir -p ${CB_OUTPUT_RESDIR}/settings > /dev/null 2> /dev/null
cp *.png ${CB_DEVEL_RESDIR}/settings/ > /dev/null 2> /dev/null
cp *.png ${CB_OUTPUT_RESDIR}/settings/ > /dev/null 2> /dev/null

exit 0


