.\" codesnippets man page. 
.\" Contact admin@codeblocks.org to correct errors or omissions. 
.TH man 1 "16 July 2007" "1.0" "cb_share_config man page"
.SH NAME
codesnippets \- Stand-alone app for the codesnippets Code::Blocks plugin.
.SH SYNOPSIS
.\" Syntax goes here. 
.B codesnippets
.SH DESCRIPTION
.B codesnippets
allows you to use codesnippets outside Code::Blocks, as a stand-alone application.
.SH AUTHOR
.nf
Pecan Heber
.fi
.SH HISTORY
2007 \- Initial version
