#!/bin/bash
mkdir -p ../../../output29
cp -f ../../../devel29/codesnippets ../../../output29/codesnippets
strip ../../../output29/codesnippets
zip -j9 ../../../devel29/share/codeblocks/codesnippets.zip ./manifest.xml
mkdir -p  ../../../devel29/share/codeblocks/images/codesnippets > /dev/null 2> /dev/null
mkdir -p ../../../output29/share/codeblocks/images/codesnippets > /dev/null 2> /dev/null
cp ./resources/*.png ../../../devel29/share/codeblocks/images/codesnippets/ > /dev/null 2> /dev/null
cp ./resources/*.png ../../../output29/share/codeblocks/images/codesnippets/ > /dev/null 2> /dev/null
exit 0
