/*
 * This file is part of the Code::Blocks IDE and licensed under the GNU Lesser General Public License, version 3
 * http://www.gnu.org/licenses/lgpl-3.0.html
 */

/** Code::Blocks SDK precompiled headers support for plugins.
  * This is precompiled with -DBUILDING_PLUGIN
  */

#ifndef SDK_H
#define SDK_H

// One PCH is enough, the sdk_precomp.h.gch is generated by building sdk, but can be used for other
// targets.
// As we use the compiler option: -include sdk_precomp.h for all the src and plugins
// source files in those targets all have #include "sdk.h" directive as there first line,
// thus we can safely add the guard here, since this header is already included(from the command line)

#ifndef SDK_PRECOMP_H
	#include "sdk_precomp.h"
#endif // SDK_PRECOMP_H


#endif // SDK_H
