#! /bin/sh
#
# This file is part of the Code::Blocks IDE and licensed under the GNU General Public License, version 3
# http://www.gnu.org/licenses/gpl-3.0.html
#
# Copyright: 2011 Jens Lody
#
# $Revision: 7326 $
# $Id: update 7326 2011-08-05 09:48:57Z jenslody $
# $HeadURL: https://mortenmacfly@svn.berlios.de/svnroot/repos/codeblocks/trunk/src/plugins/contrib/SpellChecker/update $
#

mkdir -p "../../../devel/share/codeblocks/SpellChecker"
mkdir -p "../../../output/share/codeblocks/SpellChecker"
cp *.png "../../../devel/share/codeblocks/images/settings/"
cp *.png "../../../output/share/codeblocks/images/settings/"
cp OnlineSpellChecking.xml  "../../../devel/share/codeblocks/SpellChecker/"
cp OnlineSpellChecking.xml  "../../../output/share/codeblocks/SpellChecker/"
cp rc/*.png "../../../devel/share/codeblocks/SpellChecker/"
cp rc/*.png "../../../output/share/codeblocks/SpellChecker/"
exit 0

